version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Frontend berjalan di localhost:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Backend berjalan di localhost:5000
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=lms_database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lms_database
    ports:
      - "3306:3306"
