version: "3.8"

services:
  front-end:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map port 3000 di host ke port 80 di container
    depends_on:
      - notification-service

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "4000:5003" # Map port container 5003 ke port 4000 host
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/notifications # Format mapping key-value

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
